if(NOT DEFINED JAMMERNETZ_FIXUP_BUNDLE OR JAMMERNETZ_FIXUP_BUNDLE STREQUAL "")
    message(FATAL_ERROR "JAMMERNETZ_FIXUP_BUNDLE is required")
endif()

if(NOT DEFINED JAMMERNETZ_FIXUP_SEARCH_DIRECTORIES)
    set(JAMMERNETZ_FIXUP_SEARCH_DIRECTORIES "")
endif()

include(BundleUtilities)
set(BU_CHMOD_BUNDLE_ITEMS TRUE)

message(STATUS "Making macOS bundle self-contained: ${JAMMERNETZ_FIXUP_BUNDLE}")
fixup_bundle(
    "${JAMMERNETZ_FIXUP_BUNDLE}"
    ""
    "${JAMMERNETZ_FIXUP_SEARCH_DIRECTORIES}")
